language: php

sudo: false

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: '7.3'
    - env: DBTYPE=mysql; MW=1.31.0
      php: '7.0'
  fast_finish: true

install: MW=1.32.0 DBTYPE=sqlite make init_mw

script: make test_mw

cache:
  directories:
    - $HOME/.composer/cache
