language: php

sudo: false

env:
  - DBTYPE=mysql MW=master

php:
  - 7.0
  - 7.3

matrix:
  fast_finish: true

install: make init_mw

script:
  - make cs
  - make test
  - make test_mw

cache:
  directories:
    - $HOME/.composer/cache
